version: '3.3'
# Usage for caveservice

#  -- After update just run deploy again
#   docker stack deploy --with-registry-auth -c cs-swarm.yml csstack

# docker service ls

services:
  caveservice:
    image: b33rsledge/caveservice:v2
    container_name: "caveservice"
    environment: 
      spring.redis.host: redisdb
      spring.redis.port: 6379
      spring.redis.timeout: 60000
      debug: 0
      storage.room: redisStorage
    ports:
      - 8080:8080
    networks:
      - cs-network
    depends_on:  #not working in swarm mode
      - redisdb
    command: java -jar /root/caveservice/caveservice.jar 
  redisdb:
    image: redis:6.2.5-alpine
    container_name: "caveservice-redis"
    volumes:
      - redisservice_data:/data
    networks:
      - cs-network
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8081:8080"
volumes:
  redisservice_data:
networks:
  cs-network: {}
  public:

