version: '3.3'
# Usage for caveservice

#  -- After update just run deploy again
#   docker stack deploy --with-registry-auth -c real-swarm-db.yml alfastack

# docker service ls

services:
  caveservice:
    image: ricoris/caveservice
    container_name: "caveservice"
    ports:
      - 8080:8080
    networks:
      - caveservice-network
    depends_on:  #not working in swarm mode
      - redisdb
    command: java -jar /caveservice.jar 
  redisdb:
    image: redis:6.2.5-alpine
    container_name: "caveservice-redis"
    volumes:
      - redisservice_data:/data
    networks:
      - caveservice-network

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8081:8080"

volumes:
  redisservice_data:
networks:
  caveservice-network: {}
  public:

