version: '3.3'
# Usage for caveservice

#  -- After update just run deploy again
#   docker stack deploy --with-registry-auth -c cs-swarm.yml csstack

# docker service ls

services:
  caveservice:
    image: b33rsledge/caveservice:v2
    container_name: "caveservice"
    environment: 
      spring.redis.host: rediscs
      spring.redis.port: 6380
      spring.redis.timeout: 60000
      debug: 0
      storage.room: redisStorage
    ports:
      - "8080:8080"
    networks:
      - cs-network
    depends_on:  #not working in swarm mode
      - rediscs
    command: java -jar /root/caveservice/caveservice.jar 
  rediscs:
    image: redis:6.2.5-alpine
    container_name: "cs-redis"
    command: --port 6380
    volumes:
      - redisdata_cs:/data/cs
    networks:
      - cs-network
  messageservice:
    image: christianmaintz/sky-cave-message-service:latest
    environment:
      spring.profiles.active: redis
      redis.host: redisms
      redis.port: 6381
      spring.redis.timeout: 60000
      debug: 0
    ports:
      - "5777:5777"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - cs-network
    depends_on:  #not working in swarm mode
      - redisms
    command: "java -jar  /root/message/sky-cave-message-service-1.0.0.jar"
  redisms:
    image: redis:6.2.5-alpine
    command: --port 6381
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    ports:
      - "6381"
    volumes:
      - redisdata_ms:/data/ms
    networks:
      - cs-network
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:8080"
    networks:
      - cs-network
  # We seem to be unable to specify redishost and/or redisport without rebuilding the application. This is
  # not really ci/cd friendly as we cannot configure deployment properly.
 # playerservice:
 #   image: "ligaard/player:fatjar-latest"
 #   command: java -jar /root/cave/player.jar redis-compose.cpf
 #   deploy:
 #     replicas: 1
 #     restart_policy:
 #       condition: on-failure
 #   networks:
 #     - cs-network
 #   ports:
 #     - "7778:7778"
 #   depends_on:
 #     - redis
    # Redis needs not be accessible outside stack network, so no ports defined.
    # Redis can still be accesed via: $ docker exec -ti <containerId> redis-cli
 # redis:
 #   image: "redis:6.2.6-alpine"
 #   networks:
 #     - cs-network
 #   volumes:
 #     - redisdata_pl:/data/pl
volumes:
  redisdata_cs:
    external: false
#  redisdata_pl:
#    external: false
  redisdata_ms:
    external: false
networks:
  cs-network: {}
  public:
