spring:
  main:
    banner-mode: off
  redis:
     host: localhost
     port: 6379
     timeout: 60000
server:
  error:
    include-message: always
debug: false
storage:
  #room: redisStorage
  room: memoryStorage

