spring:
  main:
    banner-mode: off
  redis:
     host: localhost
     port: 6379
     timeout: 60000
  simulation:
     delay: 10
management:
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-message: always
  port: 8080
debug: false
storage:
  room: redisStorage
  #room: memoryStorage
info:
  application:
    name: "CaveService"
    version: "v2"


